name: tt
channels:
  - soumith
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud//pytorch
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud//pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.0=py36_0
  - astor=0.8.0=py36_0
  - astroid=2.4.2=py36h9f0ad1d_0
  - bayesian-optimization=1.1.0=py_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py36h9880bd3_2
  - cffi=1.13.1=py36h2e261b9_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.0=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py_2
  - expat=2.2.9=he1b5a44_2
  - freetype=2.9.1=h8a8886c_1
  - gast=0.3.2=py_0
  - git=2.23.0=pl526hacde149_0
  - gitdb=4.0.5=py_0
  - gitpython=3.1.3=py_0
  - google-pasta=0.1.7=py_0
  - grpcio=1.16.1=py36hf8bcb03_1
  - h5py=2.9.0=py36h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=hf484d3e_1000
  - intel-openmp=2019.4=243
  - isort=5.5.1=py36h9f0ad1d_0
  - joblib=0.16.0=py_0
  - jpeg=9b=h024ee3a_2
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - krb5=1.17.1=h173b8e3_0
  - lazy-object-proxy=1.4.3=py36h8c4c3a4_2
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libcurl=7.71.1=hcdd3856_3
  - libedit=3.1.20191231=h46ee950_1
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.9.2=hd408876_0
  - libssh2=1.9.0=hab1572f_4
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - markdown=3.1.1=py36_0
  - matplotlib-base=3.1.3=py36hef1b27d_0
  - mccabe=0.6.1=py_1
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.14=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - ncurses=6.1=hf484d3e_1002
  - ninja=1.9.0=py36hfd86e86_0
  - numpy=1.17.2=py36haad9e8e_0
  - numpy-base=1.17.2=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - openssl=1.1.1h=h516909a_0
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - perl=5.26.2=h516909a_1006
  - pillow=6.2.0=py36h34e0f95_0
  - pip=19.3=py36_0
  - protobuf=3.9.2=py36he6710b0_0
  - pycparser=2.19=py36_0
  - pylint=2.6.0=py36h9f0ad1d_0
  - python=3.6.7=h357f687_1005
  - python_abi=3.6=1_cp36m
  - pytorch=1.3.0=py3.6_cuda10.1.243_cudnn7.6.3_0
  - readline=8.0=hf8c457e_0
  - scikit-learn=0.23.1=py36h0e1014b_0
  - scipy=1.3.1=py36h7c811a0_0
  - seaborn=0.11.0=ha770c72_1
  - seaborn-base=0.11.0=pyhd8ed1ab_1
  - setuptools=41.4.0=py36_0
  - six=1.12.0=py36_0
  - smmap=3.0.4=pyh9f0ad1d_0
  - sqlite=3.30.1=hcee41ef_0
  - statsmodels=0.12.1=py36ha112f06_1
  - tensorboard=1.14.0=py36hf484d3e_0
  - tensorflow=1.14.0=gpu_py36h3fb9ad6_0
  - tensorflow-base=1.14.0=gpu_py36he45bfe2_0
  - tensorflow-estimator=1.14.0=py_0
  - termcolor=1.1.0=py36_1
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.9=hed695b0_1003
  - toml=0.10.1=pyh9f0ad1d_0
  - torchvision=0.2.1=py_2
  - tornado=6.1=py36h1d69622_0
  - typed-ast=1.4.1=py36h516909a_0
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py36_0
  - wrapt=1.11.2=py36h7b6447c_0
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h516909a_1006
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - aiohttp==3.6.2
    - async-timeout==3.0.1
    - atari-py==0.2.6
    - attrs==19.3.0
    - beautifulsoup4==4.9.1
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==1.3.0
    - colorama==0.4.1
    - cython==0.29.21
    - fasteners==0.15
    - filelock==3.0.12
    - funcsigs==1.0.2
    - future==0.18.2
    - glfw==1.12.0
    - google==3.0.0
    - gtimer==1.0.0b5
    - gym==0.17.2
    - idna==2.10
    - idna-ssl==1.1.0
    - imageio==2.9.0
    - importlib-metadata==1.0.0
    - jsonschema==3.2.0
    - kiwisolver==1.1.0
    - lockfile==0.12.2
    - matplotlib==3.1.1
    - meliae==0.5.1
    - monotonic==1.5
    - more-itertools==8.0.0
    - mujoco-py==2.0.2.8
    - multidict==4.7.6
    - opencv-python==4.4.0.42
    - packaging==19.2
    - pandas==1.0.5
    - pluggy==0.13.1
    - psutil==5.6.7
    - py==1.8.0
    - py-spy==0.3.0
    - pycallgraph==1.0.1
    - pyglet==1.5.0
    - pyparsing==2.4.2
    - pyrasite==2.0
    - pyrasite-gui==2.0b7
    - pyrsistent==0.15.6
    - pystan==2.19.1.1
    - pytest==5.3.1
    - python-dateutil==2.8.0
    - pytz==2020.1
    - pyyaml==5.1.2
    - ray==0.8.3
    - redis==3.3.11
    - setproctitle==1.1.10
    - soupsieve==2.0.1
    - tensorboard-logger==0.1.0
    - tensorboardx==2.1
    - tqdm==4.48.0
    - trueskill==0.4.5
    - typing-extensions==3.7.4.2
    - urwid==2.1.1
    - wcwidth==0.1.7
    - yarl==1.5.0
    - zipp==0.6.0
prefix: /home/.../anaconda3/envs/tt

