action_selector: epsilon_greedy
agent: ant_demo
agent_id_dim: 13
agent_output_type: q
batch_size_run: 7
buffer_size: 5000
checkpoint_path: /root/pymarl-algorithm-extension-via-starcraft-master2/results/models/ant_metaq__2025-09-21_04-20-36
double_q: true
dropout: 0.0
epsilon_anneal_time: 50000
epsilon_finish: 0.05
epsilon_start: 1.0
fc_add_dim: 32
fc_c_dim: 64
fc_mul_dim: 32
ffn_dim: 64
hypernet_embed: 64
hypernet_layers: 2
last_action_extend_dim: 14
learner: metaq_v5_learner
metaq_final_layer_dim: 32
metaq_transformer_dropout: 0.0
metaq_transformer_ffn_dim: 128
metaq_transformer_model_dim: 32
metaq_transformer_n_heads: 4
mixer: metaq_v5_heter
mixing_embed_dim: 32
model_dim: 16
name: ant_metaq_28m
num_heads: 2
runner: parallel
save_model: true
t_max: 820000
target_update_interval: 200
use_tensorboard: true
